In [2]:
import pandas as pd
import sys
from pathlib import Path

sys.path.append(str(Path().resolve().parent))
pd.set_option('display.max_columns', None)

### Cargamos los datasets con los que vamos a trabajar desde la url oficial

In [3]:
collision = pd.read_csv('https://data.dft.gov.uk/road-accidents-safety-data/dft-road-casualty-statistics-collision-last-5-years.csv')
casualty = pd.read_csv('https://data.dft.gov.uk/road-accidents-safety-data/dft-road-casualty-statistics-casualty-last-5-years.csv')
vehicle = pd.read_csv('https://data.dft.gov.uk/road-accidents-safety-data/dft-road-casualty-statistics-vehicle-last-5-years.csv',  dtype={'generic_make_model': str})

Observación:
- pandas nos da un mensaje de que la columna generic_make_model tiene tipos distintos. En casos de querer utilizar la columna habrá que tenerlo en cuenta

In [4]:
#collision.to_csv('../../data/raw/uk_collision_5_raw.csv')
#casualty.to_csv('../../data/raw/uk_casualty_5_raw.csv')
#vehicle.to_csv('../../data/raw/uk_vehicle_5_raw.csv')

### Estructura

- *Dimensiones:*

In [5]:
collision.shape

(503475, 44)

In [6]:
casualty.shape

(640522, 23)

In [7]:
vehicle.shape

(920692, 32)

- *Tipos de datos:*

In [8]:
collision.dtypes

collision_index                                         str
collision_year                                        int64
collision_ref_no                                        str
location_easting_osgr                               float64
location_northing_osgr                              float64
longitude                                           float64
latitude                                            float64
police_force                                          int64
collision_severity                                    int64
number_of_vehicles                                    int64
number_of_casualties                                  int64
date                                                    str
day_of_week                                           int64
time                                                    str
local_authority_district                              int64
local_authority_ons_district                            str
local_authority_highway                                 str
local_authority_highway_current                         str
first_road_class                                      int64
first_road_number                                     int64
road_type                                             int64
speed_limit                                           int64
junction_detail_historic                              int64
junction_detail                                       int64
junction_control                                      int64
second_road_class                                     int64
second_road_number                                    int64
pedestrian_crossing_human_control_historic            int64
pedestrian_crossing_physical_facilities_historic      int64
pedestrian_crossing                                   int64
light_conditions                                      int64
weather_conditions                                    int64
road_surface_conditions                               int64
special_conditions_at_site                            int64
carriageway_hazards_historic                          int64
carriageway_hazards                                   int64
urban_or_rural_area                                   int64
did_police_officer_attend_scene_of_accident           int64
trunk_road_flag                                       int64
lsoa_of_accident_location                               str
enhanced_severity_collision                           int64
collision_injury_based                                int64
collision_adjusted_severity_serious                 float64
collision_adjusted_severity_slight                  float64
dtype: object

In [9]:
casualty.dtypes

collision_index                           str
collision_year                          int64
collision_ref_no                          str
vehicle_reference                       int64
casualty_reference                      int64
casualty_class                          int64
sex_of_casualty                         int64
age_of_casualty                         int64
age_band_of_casualty                    int64
casualty_severity                       int64
pedestrian_location                     int64
pedestrian_movement                     int64
car_passenger                           int64
bus_or_coach_passenger                  int64
pedestrian_road_maintenance_worker      int64
casualty_type                           int64
casualty_imd_decile                     int64
lsoa_of_casualty                          str
enhanced_casualty_severity              int64
casualty_injury_based                   int64
casualty_adjusted_severity_serious    float64
casualty_adjusted_severity_slight     float64
casualty_distance_banding               int64
dtype: object

In [10]:
vehicle.dtypes

collision_index                                str
collision_year                               int64
collision_ref_no                               str
vehicle_reference                            int64
vehicle_type                                 int64
towing_and_articulation                      int64
vehicle_manoeuvre_historic                   int64
vehicle_manoeuvre                            int64
vehicle_direction_from                       int64
vehicle_direction_to                         int64
vehicle_location_restricted_lane_historic    int64
vehicle_location_restricted_lane             int64
junction_location                            int64
skidding_and_overturning                     int64
hit_object_in_carriageway                    int64
vehicle_leaving_carriageway                  int64
hit_object_off_carriageway                   int64
first_point_of_impact                        int64
vehicle_left_hand_drive                      int64
journey_purpose_of_driver_historic           int64
journey_purpose_of_driver                    int64
sex_of_driver                                int64
age_of_driver                                int64
age_band_of_driver                           int64
engine_capacity_cc                           int64
propulsion_code                              int64
age_of_vehicle                               int64
generic_make_model                             str
driver_imd_decile                            int64
lsoa_of_driver                                 str
escooter_flag                                int64
driver_distance_banding                      int64
dtype: object

Parece que las columnas siguen un estándar snake_case y no va a hacer falta tratarlas

- *Muestras de 5 filas para tener un vistazo rapido de los datos*

In [1]:
collision.sample(5)

NameError: name 'collision' is not defined

In [12]:
casualty.sample(5)

,collision_index,collision_year,collision_ref_no,vehicle_reference,casualty_reference,casualty_class,sex_of_casualty,age_of_casualty,age_band_of_casualty,casualty_severity,pedestrian_location,pedestrian_movement,car_passenger,bus_or_coach_passenger,pedestrian_road_maintenance_worker,casualty_type,casualty_imd_decile,lsoa_of_casualty,enhanced_casualty_severity,casualty_injury_based,casualty_adjusted_severity_serious,casualty_adjusted_severity_slight,casualty_distance_banding
392101,2021501039480,2021,501039480,2,4,1,1,80,11,3,0,0,0,0,0,9,6,E01018858,3,1,0.0,1.0,-1
639289,2023610024823,2023,610024823,1,2,2,1,26,6,1,0,0,1,0,0,9,9,W01001514,-1,0,0.0,0.0,-1
505806,2024010554055,2024,010554055,1,1,1,2,47,8,3,0,0,0,0,0,1,3,E01003295,3,1,0.0,1.0,2
240021,2023221334429,2023,221334429,2,1,2,2,54,8,3,0,0,1,0,0,9,4,E01022251,3,1,0.0,1.0,-1
620831,2024461451142,2024,461451142,2,2,2,1,11,3,3,0,0,1,0,0,9,4,E01016116,3,1,0.0,1.0,1

In [13]:
vehicle.sample(5)

,collision_index,collision_year,collision_ref_no,vehicle_reference,vehicle_type,towing_and_articulation,vehicle_manoeuvre_historic,vehicle_manoeuvre,vehicle_direction_from,vehicle_direction_to,vehicle_location_restricted_lane_historic,vehicle_location_restricted_lane,junction_location,skidding_and_overturning,hit_object_in_carriageway,vehicle_leaving_carriageway,hit_object_off_carriageway,first_point_of_impact,vehicle_left_hand_drive,journey_purpose_of_driver_historic,journey_purpose_of_driver,sex_of_driver,age_of_driver,age_band_of_driver,engine_capacity_cc,propulsion_code,age_of_vehicle,generic_make_model,driver_imd_decile,lsoa_of_driver,escooter_flag,driver_distance_banding
539675,2023520400142,2023,520400142,2,21,0,18,19,2,6,0,0,8,0,0,0,0,1,1,6,6,1,40,7,4500,2,2,DAF TRUCKS MODEL MISSING,6,W01001593,0,-1
64761,2020450937504,2020,450937504,1,9,0,4,4,5,1,0,0,0,1,0,0,0,1,1,6,6,2,25,5,1397,1,11,MINI FIRST,6,E01031676,0,-1
132488,2021471105842,2021,471105842,2,9,0,18,19,3,7,0,0,1,0,0,0,0,1,1,5,6,2,58,9,1388,1,10,FORD FIESTA,2,E01031371,0,-1
589056,2020137CR0572,2020,137CR0572,1,9,0,1,1,2,6,0,0,0,5,0,0,0,2,1,6,6,2,95,11,1388,1,14,FORD FIESTA,7,E01011849,0,-1
718432,202063D038120,2020,63D038120,1,90,4,18,19,5,1,0,0,4,1,0,0,0,1,1,1,1,1,30,6,-1,-1,-1,-1,3,E01009930,0,-1

### ¡Importante!

Los datasets que vamos a usar tienen las variables categóricas codificadas como números. Las dejaremos en ese formato por motivos eficiencia y los reemplazaremos a sus correspondientes etiquetas solo cuando sea necesario para la operación que estemos realizando.

Existe un [excel](https://view.officeapps.live.com/op/view.aspx?src=https%3A%2F%2Fassets.publishing.service.gov.uk%2Fmedia%2F691c6440e39a085bda43eed6%2Fdft-road-casualty-statistics-road-safety-open-dataset-data-guide-2024.xlsx&wdOrigin=BROWSELINK) que contiene mapeo de esos valores categóricos. Se ha creado la funcion ```create_data_map``` en ```src/data/uk_data_mapper.py``` para obtener un diccionario clave:valor a partir de ese excel y poder reemplazar los valores facilmente.

Ejemplo de uso:

In [14]:
from src.uk_data_mapper import create_data_map

collision_value_map = create_data_map('collision', collision.columns)
casualty_value_map = create_data_map('casualty', casualty.columns)
vehicle_value_map = create_data_map('vehicle', vehicle.columns)

In [15]:
collision.head().replace(collision_value_map)
collision_value_map

{'police_force': {1: 'Metropolitan Police',
  3: 'Cumbria',
  4: 'Lancashire',
  5: 'Merseyside',
  6: 'Greater Manchester',
  7: 'Cheshire',
  10: 'Northumbria',
  11: 'Durham',
  12: 'North Yorkshire',
  13: 'West Yorkshire',
  14: 'South Yorkshire',
  16: 'Humberside',
  17: 'Cleveland',
  20: 'West Midlands',
  21: 'Staffordshire',
  22: 'West Mercia',
  23: 'Warwickshire',
  30: 'Derbyshire',
  31: 'Nottinghamshire',
  32: 'Lincolnshire',
  33: 'Leicestershire',
  34: 'Northamptonshire',
  35: 'Cambridgeshire',
  36: 'Norfolk',
  37: 'Suffolk',
  40: 'Bedfordshire',
  41: 'Hertfordshire',
  42: 'Essex',
  43: 'Thames Valley',
  44: 'Hampshire',
  45: 'Surrey',
  46: 'Kent',
  47: 'Sussex',
  48: 'City of London',
  50: 'Devon and Cornwall',
  52: 'Avon and Somerset',
  53: 'Gloucestershire',
  54: 'Wiltshire',
  55: 'Dorset',
  60: 'North Wales',
  61: 'Gwent',
  62: 'South Wales',
  63: 'Dyfed-Powys',
  91: 'Northern',
  92: 'Grampian',
  93: 'Tayside',
  94: 'Fife',
  95: 'Lothian and Borders',
  96: 'Central',
  97: 'Strathclyde',
  98: 'Dumfries and Galloway',
  99: 'Police Scotland'},
 'collision_severity': {1: 'Fatal', 2: 'Serious', 3: 'Slight'},
 'date': {'(DD/MM/YYYY)': nan},
 'day_of_week': {1: 'Sunday',
  2: 'Monday',
  3: 'Tuesday',
  4: 'Wednesday',
  5: 'Thursday',
  6: 'Friday',
  7: 'Saturday'},
 'time': {'(HH:MM)': nan},
 'local_authority_district': {1: 'Westminster',
  2: 'Camden',
  3: 'Islington',
  4: 'Hackney',
  5: 'Tower Hamlets',
  6: 'Greenwich',
  7: 'Lewisham',
  8: 'Southwark',
  9: 'Lambeth',
  10: 'Wandsworth',
  11: 'Hammersmith and Fulham',
  12: 'Kensington and Chelsea',
  13: 'Waltham Forest',
  14: 'Redbridge',
  15: 'Havering',
  16: 'Barking and Dagenham',
  17: 'Newham',
  18: 'Bexley',
  19: 'Bromley',
  20: 'Croydon',
  21: 'Sutton',
  22: 'Merton',
  23: 'Kingston upon Thames',
  24: 'Richmond upon Thames',
  25: 'Hounslow',
  26: 'Hillingdon',
  27: 'Ealing',
  28: 'Brent',
  29: 'Harrow',
  30: 'Barnet',
  31: 'Haringey',
  32: 'Enfield',
  33: 'Hertsmere',
  38: 'Epsom and Ewell',
  40: 'Spelthorne',
  57: 'London Airport (Heathrow)',
  60: 'Allerdale',
  61: 'Barrow-in-Furness',
  62: 'Carlisle',
  63: 'Copeland',
  64: 'Eden',
  65: 'South Lakeland',
  70: 'Blackburn with Darwen',
  71: 'Blackpool',
  72: 'Burnley',
  73: 'Chorley',
  74: 'Fylde',
  75: 'Hyndburn',
  76: 'Lancaster',
  77: 'Pendle',
  79: 'Preston',
  80: 'Ribble Valley',
  82: 'Rossendale',
  83: 'South Ribble',
  84: 'West Lancashire',
  85: 'Wyre',
  90: 'Knowsley',
  91: 'Liverpool',
  92: 'St. Helens',
  93: 'Sefton',
  95: 'Wirral',
  100: 'Bolton',
  101: 'Bury',
  102: 'Manchester',
  104: 'Oldham',
  106: 'Rochdale',
  107: 'Salford',
  109: 'Stockport',
  110: 'Tameside',
  112: 'Trafford',
  114: 'Wigan',
  120: 'Chester',
  121: 'Congleton',
  122: 'Crewe and Nantwich',
  123: 'Ellesmere Port and Neston',
  124: 'Halton',
  126: 'Macclesfield',
  127: 'Vale Royal',
  128: 'Warrington',
  129: 'Cheshire East',
  130: 'Cheshire West and Chester',
  139: 'Northumberland',
  140: 'Alnwick',
  141: 'Berwick-upon-Tweed',
  142: 'Blyth Valley',
  143: 'Castle Morpeth',
  144: 'Tynedale',
  145: 'Wansbeck',
  146: 'Gateshead',
  147: 'Newcastle upon Tyne',
  148: 'North Tyneside',
  149: 'South Tyneside',
  150: 'Sunderland',
  160: 'Chester-le-Street',
  161: 'Darlington',
  162: 'Derwentside',
  163: 'Durham',
  164: 'Easington',
  165: 'Sedgefield',
  166: 'Teesdale',
  168: 'Wear Valley',
  169: 'County Durham',
  180: 'Craven',
  181: 'Hambleton',
  182: 'Harrogate',
  184: 'Richmondshire',
  185: 'Ryedale',
  186: 'Scarborough',
  187: 'Selby',
  189: 'York',
  200: 'Bradford',
  202: 'Calderdale',
  203: 'Kirklees',
  204: 'Leeds',
  206: 'Wakefield',
  210: 'Barnsley',
  211: 'Doncaster',
  213: 'Rotherham',
  215: 'Sheffield',
  220: 'Beverley',
  221: 'Boothferry',
  224: 'Cleethorpes',
  225: 'Glanford',
  226: 'Grimsby',
  227: 'Holderness',
  228: 'Kingston upon Hull, City of',
  229: 'East Yorkshire',
  230: 'Scunthorpe',
  231: 'East Riding of Yorkshire',
  232: 'North Lincolnshire',
  233: 'North East Lincolnshire',
  240: 'Hartlepool',
  241: 'Redcar and Cleveland',
  243: 'Middlesbrough',
  245: 'Stockton-on-Tees',
  250: 'Cannock Chase',
  251: 'East Staffordshire',
  252: 'Lichfield',
  253: 'Newcastle-under-Lyme',
  254: 'South Staffordshire',
  255: 'Stafford',
  256: 'Staffordshire Moorlands',
  257: 'Stoke-on-Trent',
  258: 'Tamworth',
  270: 'Bromsgrove',
  271: 'Hereford',
  272: 'Leominster',
  273: 'Malvern Hills',
  274: 'Redditch',
  275: 'South Herefordshire',
  276: 'Worcester',
  277: 'Wychavon',
  278: 'Wyre Forest',
  279: 'Bridgnorth',
  280: 'North Shropshire',
  281: 'Oswestry',
  282: 'Shrewsbury and Atcham',
  283: 'South Shropshire',
  284: 'Telford and Wrekin',
  285: 'Herefordshire, County of ',
  286: 'Shropshire',
  290: 'North Warwickshire',
  291: 'Nuneaton and Bedworth',
  292: 'Rugby ',
  293: 'Stratford-upon-Avon',
  294: 'Warwick',
  300: 'Birmingham',
  302: 'Coventry',
  303: 'Dudley',
  305: 'Sandwell',
  306: 'Solihull',
  307: 'Walsall',
  309: 'Wolverhampton',
  320: 'Amber Valley',
  321: 'Bolsover',
  322: 'Chesterfield',
  323: 'Derby',
  324: 'Erewash',
  325: 'High Peak',
  327: 'North East Derbyshire',
  328: 'South Derbyshire',
  329: 'Derbyshire Dales',
  340: 'Ashfield',
  341: 'Bassetlaw',
  342: 'Broxtowe',
  343: 'Gedling',
  344: 'Mansfield',
  345: 'Newark and Sherwood',
  346: 'Nottingham',
  347: 'Rushcliffe',
  350: 'Boston',
  351: 'East Lindsey',
  352: 'Lincoln',
  353: 'North Kesteven',
  354: 'South Holland',
  355: 'South Kesteven',
  356: 'West Lindsey',
  360: 'Blaby',
  361: 'Hinckley and Bosworth',
  362: 'Charnwood',
  363: 'Harborough',
  364: 'Leicester',
  365: 'Melton',
  366: 'North West Leicestershire',
  367: 'Oadby and Wigston',
  368: 'Rutland',
  380: 'Corby',
  381: 'Daventry',
  382: 'East Northamptonshire',
  383: 'Kettering',
  384: 'Northampton',
  385: 'South Northamptonshire',
  386: 'Wellingborough',
  390: 'Cambridge',
  391: 'East Cambridgeshire',
  392: 'Fenland',
  393: 'Huntingdonshire',
  394: 'Peterborough',
  395: 'South Cambridgeshire',
  400: 'Breckland',
  401: 'Broadland',
  402: 'Great Yarmouth',
  404: 'Norwich',
  405: 'North Norfolk',
  406: 'South Norfolk',
  407: "King's Lynn and West Norfolk",
  410: 'Babergh',
  411: 'Forest Heath',
  412: 'Ipswich',
  413: 'Mid Suffolk',
  414: 'St. Edmundsbury',
  415: 'Suffolk Coastal',
  416: 'Waveney',
  420: 'Bedford',
  421: 'Luton',
  422: 'Mid Bedfordshire',
  423: 'South Bedfordshire',
  424: 'Central Bedfordshire',
  430: 'Broxbourne',
  431: 'Dacorum',
  432: 'East Hertfordshire',
  433: 'North Hertfordshire',
  434: 'St. Albans',
  435: 'Stevenage',
  436: 'Three Rivers',
  437: 'Watford',
  438: 'Welwyn Hatfield',
  450: 'Basildon',
  451: 'Braintree',
  452: 'Brentwood',
  453: 'Castle Point',
  454: 'Chelmsford',
  455: 'Colchester',
  456: 'Epping Forest',
  457: 'Harlow',
  458: 'Maldon',
  459: 'Rochford',
  460: 'Southend-on-Sea',
  461: 'Tendring',
  462: 'Thurrock',
  463: 'Uttlesford',
  470: 'Bracknell Forest',
  471: 'West Berkshire',
  472: 'Reading',
  473: 'Slough',
  474: 'Windsor and Maidenhead',
  475: 'Wokingham',
  476: 'Aylesbury Vale',
  477: 'South Bucks',
  478: 'Chiltern',
  479: 'Milton Keynes',
  480: 'Wycombe',
  481: 'Cherwell',
  482: 'Oxford',
  483: 'Vale of White Horse',
  484: 'South Oxfordshire',
  485: 'West Oxfordshire',
  490: 'Basingstoke and Deane',
  491: 'Eastleigh',
  492: 'Fareham',
  493: 'Gosport',
  494: 'Hart',
  495: 'Havant',
  496: 'New Forest',
  497: 'East Hampshire',
  498: 'Portsmouth',
  499: 'Rushmoor',
  500: 'Southampton ',
  501: 'Test Valley',
  502: 'Winchester',
  503: 'Medina',
  504: 'South Wight',
  505: 'Isle of Wight',
  510: 'Elmbridge',
  511: 'Guildford',
  512: 'Mole Valley',
  513: 'Reigate and Banstead',
  514: 'Runnymede',
  515: 'Surrey Heath',
  516: 'Tandridge',
  517: 'Waverley',
  518: 'Woking',
  530: 'Ashford',
  531: 'Canterbury',
  532: 'Dartford',
  533: 'Dover',
  534: 'Gillingham',
  535: 'Gravesham',
  536: 'Maidstone',
  537: 'Rochester',
  538: 'Sevenoaks',
  539: 'Shepway',
  540: 'Swale',
  541: 'Thanet',
  542: 'Tonbridge and Malling',
  543: 'Tunbridge Wells',
  544: 'Medway',
  550: 'Brighton',
  551: 'Eastbourne',
  552: 'Hastings',
  553: 'Hove',
  554: 'Lewes',
  555: 'Rother',
  556: 'Wealden',
  557: 'Adur',
  558: 'Arun',
  559: 'Chichester',
  560: 'Crawley',
  562: 'Horsham',
  563: 'Mid Sussex',
  564: 'Worthing',
  565: 'Brighton and Hove',
  570: 'City of London',
  580: 'East Devon',
  581: 'Exeter',
  582: 'North Devon',
  583: 'Plymouth',
  584: 'South Hams',
  585: 'Teignbridge',
  586: 'Mid Devon',
  587: 'Torbay',
  588: 'Torridge',
  589: 'West Devon',
  590: 'Caradon',
  591: 'Carrick',
  592: 'Kerrier',
  593: 'North Cornwall',
  594: 'Penwith',
  595: 'Restormel',
  596: 'Cornwall',
  599: 'Isles of Scilly',
  600: 'Bath',
  601: 'Bristol, City of',
  602: 'Kingswood',
  603: 'Northavon',
  604: 'Wansdyke',
  605: 'North Somerset',
  606: 'Mendip',
  607: 'Sedgemoor',
  608: 'Taunton Deane',
  609: 'West Somerset',
  610: 'South Somerset',
  611: 'Bath and North East Somerset',
  612: 'South Gloucestershire',
  620: 'Cheltenham',
  621: 'Cotswold',
  622: 'Forest of Dean',
  623: 'Gloucester',
  624: 'Stroud',
  625: 'Tewkesbury',
  630: 'Kennet',
  631: 'North Wiltshire',
  632: 'Salisbury',
  633: 'Swindon',
  634: 'West Wiltshire',
  635: 'Wiltshire',
  640: 'Bournemouth',
  641: 'Christchurch',
  642: 'North Dorset',
  643: 'Poole',
  644: 'Purbeck',
  645: 'West Dorset',
  646: 'Weymouth and Portland',
  647: 'East Dorset',
  660: 'Aberconwy',
  661: 'Arfon',
  662: 'Dwyfor',
  663: 'Meirionnydd',
  664: 'Ynys Mon - Isle of Anglesey ',
  665: 'Alyn-Deeside',
  666: 'Colwyn',
  667: 'Delwyn',
  668: 'Glyndwr',
  669: 'Rhuddlan',
  670: 'Wrexham Maelor',
  680: 'Blaenau Gwent',
  682: 'Islwyn',
  683: 'Monmouth',
  684: 'Newport',
  685: 'Torfaen',
  690: 'Cynon Valley',
  692: 'Merthyr Tydfil',
  694: 'Ogwr',
  695: 'Rhondda',
  696: 'Rhymney Valley',
  698: 'Taff-Ely',
  699: 'Cardiff',
  701: 'Vale of Glamorgan',
  702: 'Afan',
  703: 'Lliw Valley',
  704: 'Neath',
  705: 'Swansea ',
  710: 'Carmarthen',
  711: 'Ceredigion',
  712: 'Dinefwr',
  713: 'Llanelli',
  714: 'Preseli',
  715: 'South Pembrokeshire',
  716: 'Brecknock',
  717: 'Montgomery',
  718: 'Radnor',
  720: 'Isle of Anglesey',
  721: 'Conwy',
  722: 'Gwynedd',
  723: 'Denbighshire',
  724: 'Flintshire',
  725: 'Wrexham',
  730: 'Blaenau Gwent',
  731: 'Caerphilly',
  732: 'Monmouthshire',
  733: 'Newport',
  734: 'Torfaen',
  740: 'Bridgend',
  741: 'Cardiff',
  742: 'Merthyr Tydfil',
  743: 'Neath Port Talbot',
  744: 'Rhondda, Cynon, Taff',
  745: 'Swansea',
  746: 'The Vale of Glamorgan',
  750: 'Ceredigion',
  751: 'Carmarthenshire',
  752: 'Pembrokeshire',
  753: 'Powys',
  801: 'Orkney',
  802: 'Shetland',
  803: 'Western Isles',
  804: 'Caithness',
  805: 'Sutherland',
  806: 'Ross and Cromarty',
  807: 'Skye and Lochalsh',
  808: 'Lochaber',
  809: 'Inverness',
  810: 'Badenoch and Strathspey',
  811: 'Nairn',
  812: 'Aberdeen (City of)',
  813: 'Moray',
  814: 'Banff and Buchan',
  815: 'Gordon',
  816: 'Kincardine and Deeside',
  817: 'Dundee (City of)',
  818: 'Angus',
  819: 'Perth and Kinross',
  821: 'Kirkcaldy',
  822: 'North East Fife',
  823: 'Dunfermline ',
  824: 'Edinburgh (City of)',
  825: 'West Lothian',
  826: 'Midlothian',
  827: 'East Lothian',
  828: 'Tweeddale',
  829: 'Ettrick and Lauderdale',
  830: 'Roxburgh',
  831: 'Berwickshire',
  833: 'Clackmannan',
  834: 'Stirling',
  835: 'Falkirk',
  836: 'Glasgow (City of)',
  837: 'Argyll and Bute',
  838: 'Dumbarton',
  839: 'Clydebank',
  840: 'Bearsden and Milngavie',
  841: 'Strathkelvin',
  842: 'Cumbernauld and Kilsyth',
  843: 'Monklands',
  844: 'Motherwell',
  845: 'Hamilton',
  846: 'East Kilbride',
  847: 'Eastwood',
  848: 'Lanark',
  849: 'Renfrew',
  850: 'Inverclyde',
  851: 'Cunninghame',
  852: 'Kilmarnock and Loudoun',
  853: 'Kyle and Carrick',
  854: 'Cumnock and Doon Valley',
  856: 'Wigtown',
  857: 'Stewartry',
  858: 'Nithsdale',
  859: 'Annandale and Eskdale',
  910: 'Aberdeen City',
  911: 'Aberdeenshire',
  912: 'Angus',
  913: 'Argyll and Bute',
  914: 'Scottish Borders',
  915: 'Clackmannanshire',
  916: 'West Dunbartonshire',
  917: 'Dumfries and Galloway',
  918: 'Dundee City',
  919: 'East Ayrshire',
  920: 'East Dunbartonshire',
  921: 'East Lothian',
  922: 'East Renfrewshire',
  923: 'Edinburgh, City of',
  924: 'Falkirk',
  925: 'Fife',
  926: 'Glasgow City',
  927: 'Highland',
  928: 'Inverclyde',
  929: 'Midlothian',
  930: 'Moray',
  931: 'North Ayrshire',
  932: 'North Lanarkshire',
  933: 'Orkney Islands',
  934: 'Perth and Kinross',
  935: 'Renfrewshire',
  936: 'Shetland Islands',
  937: 'South Ayrshire',
  938: 'South Lanarkshire',
  939: 'Stirling',
  940: 'West Lothian',
  941: 'Western Isles',
  -1: 'Code deprecated'},
 'local_authority_ons_district': {'E06000001': 'Hartlepool',
  'E06000002': 'Middlesbrough',
  'E06000003': 'Redcar and Cleveland',
  'E06000004': 'Stockton-on-Tees',
  'E06000005': 'Darlington',
  'E06000006': 'Halton',
  'E06000007': 'Warrington',
  'E06000008': 'Blackburn with Darwen',
  'E06000009': 'Blackpool',
  'E06000010': 'Kingston upon Hull, City of',
  'E06000011': 'East Riding of Yorkshire',
  'E06000012': 'North East Lincolnshire',
  'E06000013': 'North Lincolnshire',
  'E06000014': 'York',
  'E06000015': 'Derby',
  'E06000016': 'Leicester',
  'E06000017': 'Rutland',
  'E06000018': 'Nottingham',
  'E06000019': 'Herefordshire, County of ',
  'E06000020': 'Telford and Wrekin',
  'E06000021': 'Stoke-on-Trent',
  'E06000022': 'Bath and North East Somerset',
  'E06000023': 'Bristol, City of',
  'E06000024': 'North Somerset',
  'E06000025': 'South Gloucestershire',
  'E06000026': 'Plymouth',
  'E06000027': 'Torbay',
  'E06000028': 'Bournemouth',
  'E06000029': 'Poole',
  'E06000030': 'Swindon',
  'E06000031': 'Peterborough',
  'E06000032': 'Luton',
  'E06000033': 'Southend-on-Sea',
  'E06000034': 'Thurrock',
  'E06000035': 'Medway',
  'E06000036': 'Bracknell Forest',
  'E06000037': 'West Berkshire',
  'E06000038': 'Reading',
  'E06000039': 'Slough',
  'E06000040': 'Windsor and Maidenhead',
  'E06000041': 'Wokingham',
  'E06000042': 'Milton Keynes',
  'E06000043': 'Brighton and Hove',
  'E06000044': 'Portsmouth',
  'E06000045': 'Southampton ',
  'E06000046': 'Isle of Wight',
  'E06000047': 'County Durham',
  'E06000048': 'Northumberland',
  'E06000049': 'Cheshire East',
  'E06000050': 'Cheshire West and Chester',
  'E06000051': 'Shropshire',
  'E06000052': 'Cornwall',
  'E06000053': 'Isles of Scilly',
  'E06000054': 'Wiltshire',
  'E06000055': 'Bedford',
  'E06000056': 'Central Bedfordshire',
  'E06000057': 'Northumberland',
  'E06000058': 'Bournemouth, Christchurch and Poole',
  'E06000059': 'Dorset (excluding Christchurch)',
  'E06000060': 'Buckinghamshire',
  'E06000061': 'North Northamptonshire',
  'E06000062': 'West Northamptonshire',
  'E06000063': 'Cumberland',
  'E06000064': 'Westmorland and Furness',
  'E06000065': 'North Yorkshire',
  'E06000066': 'Somerset',
  'E07000001': 'Mid Bedfordshire',
  'E07000002': 'Bedford',
  'E07000003': 'South Bedfordshire',
  'E07000004': 'Aylesbury Vale',
  'E07000005': 'Chiltern',
  'E07000006': 'South Bucks',
  'E07000007': 'Wycombe',
  'E07000008': 'Cambridge',
  'E07000009': 'East Cambridgeshire',
  'E07000010': 'Fenland',
  'E07000011': 'Huntingdonshire',
  'E07000012': 'South Cambridgeshire',
  'E07000019': 'Caradon',
  'E07000020': 'Carrick',
  'E07000021': 'Kerrier',
  'E07000022': 'North Cornwall',
  'E07000023': 'Penwith',
  'E07000024': 'Restormel',
  'E07000026': 'Allerdale',
  'E07000027': 'Barrow-in-Furness',
  'E07000028': 'Carlisle',
  'E07000029': 'Copeland',
  'E07000030': 'Eden',
  'E07000031': 'South Lakeland',
  'E07000032': 'Amber Valley',
  'E07000033': 'Bolsover',
  'E07000034': 'Chesterfield',
  'E07000035': 'Derbyshire Dales',
  'E07000036': 'Erewash',
  'E07000037': 'High Peak',
  'E07000038': 'North East Derbyshire',
  'E07000039': 'South Derbyshire',
  'E07000040': 'East Devon',
  'E07000041': 'Exeter',
  'E07000042': 'Mid Devon',
  'E07000043': 'North Devon',
  'E07000044': 'South Hams',
  'E07000045': 'Teignbridge',
  'E07000046': 'Torridge',
  'E07000047': 'West Devon',
  'E07000048': 'Christchurch',
  'E07000049': 'East Dorset',
  'E07000050': 'North Dorset',
  'E07000051': 'Purbeck',
  'E07000052': 'West Dorset',
  'E07000053': 'Weymouth and Portland',
  'E07000054': 'Chester-le-Street',
  'E07000055': 'Derwentside',
  'E07000056': 'Durham',
  'E07000057': 'Easington',
  'E07000058': 'Sedgefield',
  'E07000059': 'Teesdale',
  'E07000060': 'Wear Valley',
  'E07000061': 'Eastbourne',
  'E07000062': 'Hastings',
  'E07000063': 'Lewes',
  'E07000064': 'Rother',
  'E07000065': 'Wealden',
  'E07000066': 'Basildon',
  'E07000067': 'Braintree',
  'E07000068': 'Brentwood',
  'E07000069': 'Castle Point',
  'E07000070': 'Chelmsford',
  'E07000071': 'Colchester',
  'E07000072': 'Epping Forest',
  'E07000073': 'Harlow',
  'E07000074': 'Maldon',
  'E07000075': 'Rochford',
  'E07000076': 'Tendring',
  'E07000077': 'Uttlesford',
  'E07000078': 'Cheltenham',
  'E07000079': 'Cotswold',
  'E07000080': 'Forest of Dean',
  'E07000081': 'Gloucester',
  'E07000082': 'Stroud',
  'E07000083': 'Tewkesbury',
  'E07000084': 'Basingstoke and Deane',
  'E07000085': 'East Hampshire',
  'E07000086': 'Eastleigh',
  'E07000087': 'Fareham',
  'E07000088': 'Gosport',
  'E07000089': 'Hart',
  'E07000090': 'Havant',
  'E07000091': 'New Forest',
  'E07000092': 'Rushmoor',
  'E07000093': 'Test Valley',
  'E07000094': 'Winchester',
  'E07000095': 'Broxbourne',
  'E07000096': 'Dacorum',
  'E07000097': 'East Hertfordshire',
  'E07000098': 'Hertsmere',
  'E07000099': 'North Hertfordshire',
  'E07000100': 'St Albans',
  'E07000101': 'Stevenage',
  'E07000102': 'Three Rivers',
  'E07000103': 'Watford',
  'E07000104': 'Welwyn Hatfield',
  'E07000105': 'Ashford',
  'E07000106': 'Canterbury',
  'E07000107': 'Dartford',
  'E07000108': 'Dover',
  'E07000109': 'Gravesham',
  'E07000110': 'Maidstone',
  'E07000111': 'Sevenoaks',
  'E07000112': 'Shepway',
  'E07000113': 'Swale',
  'E07000114': 'Thanet',
  'E07000115': 'Tonbridge and Malling',
  'E07000116': 'Tunbridge Wells',
  'E07000117': 'Burnley',
  'E07000118': 'Chorley',
  'E07000119': 'Fylde',
  'E07000120': 'Hyndburn',
  'E07000121': 'Lancaster',
  'E07000122': 'Pendle',
  'E07000123': 'Preston',
  'E07000124': 'Ribble Valley',
  'E07000125': 'Rossendale',
  'E07000126': 'South Ribble',
  'E07000127': 'West Lancashire',
  'E07000128': 'Wyre',
  'E07000129': 'Blaby',
  'E07000130': 'Charnwood',
  'E07000131': 'Harborough',
  'E07000132': 'Hinckley and Bosworth',
  'E07000133': 'Melton',
  'E07000134': 'North West Leicestershire',
  'E07000135': 'Oadby and Wigston',
  'E07000136': 'Boston',
  'E07000137': 'East Lindsey',
  'E07000138': 'Lincoln',
  'E07000139': 'North Kesteven',
  'E07000140': 'South Holland',
  'E07000141': 'South Kesteven',
  'E07000142': 'West Lindsey',
  'E07000143': 'Breckland',
  'E07000144': 'Broadland',
  'E07000145': 'Great Yarmouth',
  'E07000146': "King's Lynn and West Norfolk",
  'E07000147': 'North Norfolk',
  'E07000148': 'Norwich',
  'E07000149': 'South Norfolk',
  'E07000150': 'Corby',
  'E07000151': 'Daventry',
  'E07000152': 'East Northamptonshire',
  'E07000153': 'Kettering',
  'E07000154': 'Northampton',
  'E07000155': 'South Northamptonshire',
  'E07000156': 'Wellingborough',
  'E07000163': 'Craven',
  'E07000164': 'Hambleton',
  'E07000165': 'Harrogate',
  'E07000166': 'Richmondshire',
  'E07000167': 'Ryedale',
  'E07000168': 'Scarborough',
  'E07000169': 'Selby',
  'E07000170': 'Ashfield',
  'E07000171': 'Bassetlaw',
  'E07000172': 'Broxtowe',
  'E07000173': 'Gedling',

In [16]:
casualty.head().replace(casualty_value_map)

,collision_index,collision_year,collision_ref_no,vehicle_reference,casualty_reference,casualty_class,sex_of_casualty,age_of_casualty,age_band_of_casualty,casualty_severity,pedestrian_location,pedestrian_movement,car_passenger,bus_or_coach_passenger,pedestrian_road_maintenance_worker,casualty_type,casualty_imd_decile,lsoa_of_casualty,enhanced_casualty_severity,casualty_injury_based,casualty_adjusted_severity_serious,casualty_adjusted_severity_slight,casualty_distance_banding
0,2020010280094,2020,010280094,1,1,Pedestrian,Female,24,21 - 25,Slight,"In centre of carriageway - not on refuge, isla...",Unknown or other,Not car passenger,Not a bus or coach passenger,No / Not applicable,Pedestrian,More deprived 20-30%,E01003536,Data missing or out of range,Based on severity reporting,0.0,1.0,Data missing or out of range
1,202031D109620,2020,31D109620,1,1,Pedestrian,Female,95,Over 75,Serious,"In carriageway, crossing elsewhere",Crossing from driver's nearside,Not car passenger,Not a bus or coach passenger,No / Not applicable,Pedestrian,Less deprived 40-50%,E01028156,Data missing or out of range,Based on severity reporting,1.0,0.0,Data missing or out of range
2,2020401003715,2020,401003715,1,1,Pedestrian,Male,39,36 - 45,Slight,"In carriageway, crossing elsewhere",Crossing from driver's nearside,Not car passenger,Not a bus or coach passenger,No / Not applicable,Pedestrian,More deprived 10-20%,E01017492,Slight,Based on Injury code reporting,0.0,1.0,Data missing or out of range
3,2021201086330,2021,201086330,1,1,Pedestrian,Male,63,56 - 65,Slight,On footway or verge,Unknown or other,Not car passenger,Not a bus or coach passenger,Not Known,Pedestrian,More deprived 20-30%,E01009140,Slight,Based on Injury code reporting,0.0,1.0,Data missing or out of range
4,2021371050963,2021,371050963,1,1,Pedestrian,Male,51,46 - 55,Slight,"In carriageway, not crossing",Unknown or other,Not car passenger,Not a bus or coach passenger,No / Not applicable,Pedestrian,Less deprived 10-20%,E01030190,Slight,Based on Injury code reporting,0.0,1.0,Data missing or out of range

In [17]:
collision.head().replace(collision_value_map)
collision_value_map

{'police_force': {1: 'Metropolitan Police',
  3: 'Cumbria',
  4: 'Lancashire',
  5: 'Merseyside',
  6: 'Greater Manchester',
  7: 'Cheshire',
  10: 'Northumbria',
  11: 'Durham',
  12: 'North Yorkshire',
  13: 'West Yorkshire',
  14: 'South Yorkshire',
  16: 'Humberside',
  17: 'Cleveland',
  20: 'West Midlands',
  21: 'Staffordshire',
  22: 'West Mercia',
  23: 'Warwickshire',
  30: 'Derbyshire',
  31: 'Nottinghamshire',
  32: 'Lincolnshire',
  33: 'Leicestershire',
  34: 'Northamptonshire',
  35: 'Cambridgeshire',
  36: 'Norfolk',
  37: 'Suffolk',
  40: 'Bedfordshire',
  41: 'Hertfordshire',
  42: 'Essex',
  43: 'Thames Valley',
  44: 'Hampshire',
  45: 'Surrey',
  46: 'Kent',
  47: 'Sussex',
  48: 'City of London',
  50: 'Devon and Cornwall',
  52: 'Avon and Somerset',
  53: 'Gloucestershire',
  54: 'Wiltshire',
  55: 'Dorset',
  60: 'North Wales',
  61: 'Gwent',
  62: 'South Wales',
  63: 'Dyfed-Powys',
  91: 'Northern',
  92: 'Grampian',
  93: 'Tayside',
  94: 'Fife',
  95: 'Lothian and Borders',
  96: 'Central',
  97: 'Strathclyde',
  98: 'Dumfries and Galloway',
  99: 'Police Scotland'},
 'collision_severity': {1: 'Fatal', 2: 'Serious', 3: 'Slight'},
 'date': {'(DD/MM/YYYY)': nan},
 'day_of_week': {1: 'Sunday',
  2: 'Monday',
  3: 'Tuesday',
  4: 'Wednesday',
  5: 'Thursday',
  6: 'Friday',
  7: 'Saturday'},
 'time': {'(HH:MM)': nan},
 'local_authority_district': {1: 'Westminster',
  2: 'Camden',
  3: 'Islington',
  4: 'Hackney',
  5: 'Tower Hamlets',
  6: 'Greenwich',
  7: 'Lewisham',
  8: 'Southwark',
  9: 'Lambeth',
  10: 'Wandsworth',
  11: 'Hammersmith and Fulham',
  12: 'Kensington and Chelsea',
  13: 'Waltham Forest',
  14: 'Redbridge',
  15: 'Havering',
  16: 'Barking and Dagenham',
  17: 'Newham',
  18: 'Bexley',
  19: 'Bromley',
  20: 'Croydon',
  21: 'Sutton',
  22: 'Merton',
  23: 'Kingston upon Thames',
  24: 'Richmond upon Thames',
  25: 'Hounslow',
  26: 'Hillingdon',
  27: 'Ealing',
  28: 'Brent',
  29: 'Harrow',
  30: 'Barnet',
  31: 'Haringey',
  32: 'Enfield',
  33: 'Hertsmere',
  38: 'Epsom and Ewell',
  40: 'Spelthorne',
  57: 'London Airport (Heathrow)',
  60: 'Allerdale',
  61: 'Barrow-in-Furness',
  62: 'Carlisle',
  63: 'Copeland',
  64: 'Eden',
  65: 'South Lakeland',
  70: 'Blackburn with Darwen',
  71: 'Blackpool',
  72: 'Burnley',
  73: 'Chorley',
  74: 'Fylde',
  75: 'Hyndburn',
  76: 'Lancaster',
  77: 'Pendle',
  79: 'Preston',
  80: 'Ribble Valley',
  82: 'Rossendale',
  83: 'South Ribble',
  84: 'West Lancashire',
  85: 'Wyre',
  90: 'Knowsley',
  91: 'Liverpool',
  92: 'St. Helens',
  93: 'Sefton',
  95: 'Wirral',
  100: 'Bolton',
  101: 'Bury',
  102: 'Manchester',
  104: 'Oldham',
  106: 'Rochdale',
  107: 'Salford',
  109: 'Stockport',
  110: 'Tameside',
  112: 'Trafford',
  114: 'Wigan',
  120: 'Chester',
  121: 'Congleton',
  122: 'Crewe and Nantwich',
  123: 'Ellesmere Port and Neston',
  124: 'Halton',
  126: 'Macclesfield',
  127: 'Vale Royal',
  128: 'Warrington',
  129: 'Cheshire East',
  130: 'Cheshire West and Chester',
  139: 'Northumberland',
  140: 'Alnwick',
  141: 'Berwick-upon-Tweed',
  142: 'Blyth Valley',
  143: 'Castle Morpeth',
  144: 'Tynedale',
  145: 'Wansbeck',
  146: 'Gateshead',
  147: 'Newcastle upon Tyne',
  148: 'North Tyneside',
  149: 'South Tyneside',
  150: 'Sunderland',
  160: 'Chester-le-Street',
  161: 'Darlington',
  162: 'Derwentside',
  163: 'Durham',
  164: 'Easington',
  165: 'Sedgefield',
  166: 'Teesdale',
  168: 'Wear Valley',
  169: 'County Durham',
  180: 'Craven',
  181: 'Hambleton',
  182: 'Harrogate',
  184: 'Richmondshire',
  185: 'Ryedale',
  186: 'Scarborough',
  187: 'Selby',
  189: 'York',
  200: 'Bradford',
  202: 'Calderdale',
  203: 'Kirklees',
  204: 'Leeds',
  206: 'Wakefield',
  210: 'Barnsley',
  211: 'Doncaster',
  213: 'Rotherham',
  215: 'Sheffield',
  220: 'Beverley',
  221: 'Boothferry',
  224: 'Cleethorpes',
  225: 'Glanford',
  226: 'Grimsby',
  227: 'Holderness',
  228: 'Kingston upon Hull, City of',
  229: 'East Yorkshire',
  230: 'Scunthorpe',
  231: 'East Riding of Yorkshire',
  232: 'North Lincolnshire',
  233: 'North East Lincolnshire',
  240: 'Hartlepool',
  241: 'Redcar and Cleveland',
  243: 'Middlesbrough',
  245: 'Stockton-on-Tees',
  250: 'Cannock Chase',
  251: 'East Staffordshire',
  252: 'Lichfield',
  253: 'Newcastle-under-Lyme',
  254: 'South Staffordshire',
  255: 'Stafford',
  256: 'Staffordshire Moorlands',
  257: 'Stoke-on-Trent',
  258: 'Tamworth',
  270: 'Bromsgrove',
  271: 'Hereford',
  272: 'Leominster',
  273: 'Malvern Hills',
  274: 'Redditch',
  275: 'South Herefordshire',
  276: 'Worcester',
  277: 'Wychavon',
  278: 'Wyre Forest',
  279: 'Bridgnorth',
  280: 'North Shropshire',
  281: 'Oswestry',
  282: 'Shrewsbury and Atcham',
  283: 'South Shropshire',
  284: 'Telford and Wrekin',
  285: 'Herefordshire, County of ',
  286: 'Shropshire',
  290: 'North Warwickshire',
  291: 'Nuneaton and Bedworth',
  292: 'Rugby ',
  293: 'Stratford-upon-Avon',
  294: 'Warwick',
  300: 'Birmingham',
  302: 'Coventry',
  303: 'Dudley',
  305: 'Sandwell',
  306: 'Solihull',
  307: 'Walsall',
  309: 'Wolverhampton',
  320: 'Amber Valley',
  321: 'Bolsover',
  322: 'Chesterfield',
  323: 'Derby',
  324: 'Erewash',
  325: 'High Peak',
  327: 'North East Derbyshire',
  328: 'South Derbyshire',
  329: 'Derbyshire Dales',
  340: 'Ashfield',
  341: 'Bassetlaw',
  342: 'Broxtowe',
  343: 'Gedling',
  344: 'Mansfield',
  345: 'Newark and Sherwood',
  346: 'Nottingham',
  347: 'Rushcliffe',
  350: 'Boston',
  351: 'East Lindsey',
  352: 'Lincoln',
  353: 'North Kesteven',
  354: 'South Holland',
  355: 'South Kesteven',
  356: 'West Lindsey',
  360: 'Blaby',
  361: 'Hinckley and Bosworth',
  362: 'Charnwood',
  363: 'Harborough',
  364: 'Leicester',
  365: 'Melton',
  366: 'North West Leicestershire',
  367: 'Oadby and Wigston',
  368: 'Rutland',
  380: 'Corby',
  381: 'Daventry',
  382: 'East Northamptonshire',
  383: 'Kettering',
  384: 'Northampton',
  385: 'South Northamptonshire',
  386: 'Wellingborough',
  390: 'Cambridge',
  391: 'East Cambridgeshire',
  392: 'Fenland',
  393: 'Huntingdonshire',
  394: 'Peterborough',
  395: 'South Cambridgeshire',
  400: 'Breckland',
  401: 'Broadland',
  402: 'Great Yarmouth',
  404: 'Norwich',
  405: 'North Norfolk',
  406: 'South Norfolk',
  407: "King's Lynn and West Norfolk",
  410: 'Babergh',
  411: 'Forest Heath',
  412: 'Ipswich',
  413: 'Mid Suffolk',
  414: 'St. Edmundsbury',
  415: 'Suffolk Coastal',
  416: 'Waveney',
  420: 'Bedford',
  421: 'Luton',
  422: 'Mid Bedfordshire',
  423: 'South Bedfordshire',
  424: 'Central Bedfordshire',
  430: 'Broxbourne',
  431: 'Dacorum',
  432: 'East Hertfordshire',
  433: 'North Hertfordshire',
  434: 'St. Albans',
  435: 'Stevenage',
  436: 'Three Rivers',
  437: 'Watford',
  438: 'Welwyn Hatfield',
  450: 'Basildon',
  451: 'Braintree',
  452: 'Brentwood',
  453: 'Castle Point',
  454: 'Chelmsford',
  455: 'Colchester',
  456: 'Epping Forest',
  457: 'Harlow',
  458: 'Maldon',
  459: 'Rochford',
  460: 'Southend-on-Sea',
  461: 'Tendring',
  462: 'Thurrock',
  463: 'Uttlesford',
  470: 'Bracknell Forest',
  471: 'West Berkshire',
  472: 'Reading',
  473: 'Slough',
  474: 'Windsor and Maidenhead',
  475: 'Wokingham',
  476: 'Aylesbury Vale',
  477: 'South Bucks',
  478: 'Chiltern',
  479: 'Milton Keynes',
  480: 'Wycombe',
  481: 'Cherwell',
  482: 'Oxford',
  483: 'Vale of White Horse',
  484: 'South Oxfordshire',
  485: 'West Oxfordshire',
  490: 'Basingstoke and Deane',
  491: 'Eastleigh',
  492: 'Fareham',
  493: 'Gosport',
  494: 'Hart',
  495: 'Havant',
  496: 'New Forest',
  497: 'East Hampshire',
  498: 'Portsmouth',
  499: 'Rushmoor',
  500: 'Southampton ',
  501: 'Test Valley',
  502: 'Winchester',
  503: 'Medina',
  504: 'South Wight',
  505: 'Isle of Wight',
  510: 'Elmbridge',
  511: 'Guildford',
  512: 'Mole Valley',
  513: 'Reigate and Banstead',
  514: 'Runnymede',
  515: 'Surrey Heath',
  516: 'Tandridge',
  517: 'Waverley',
  518: 'Woking',
  530: 'Ashford',
  531: 'Canterbury',
  532: 'Dartford',
  533: 'Dover',
  534: 'Gillingham',
  535: 'Gravesham',
  536: 'Maidstone',
  537: 'Rochester',
  538: 'Sevenoaks',
  539: 'Shepway',
  540: 'Swale',
  541: 'Thanet',
  542: 'Tonbridge and Malling',
  543: 'Tunbridge Wells',
  544: 'Medway',
  550: 'Brighton',
  551: 'Eastbourne',
  552: 'Hastings',
  553: 'Hove',
  554: 'Lewes',
  555: 'Rother',
  556: 'Wealden',
  557: 'Adur',
  558: 'Arun',
  559: 'Chichester',
  560: 'Crawley',
  562: 'Horsham',
  563: 'Mid Sussex',
  564: 'Worthing',
  565: 'Brighton and Hove',
  570: 'City of London',
  580: 'East Devon',
  581: 'Exeter',
  582: 'North Devon',
  583: 'Plymouth',
  584: 'South Hams',
  585: 'Teignbridge',
  586: 'Mid Devon',
  587: 'Torbay',
  588: 'Torridge',
  589: 'West Devon',
  590: 'Caradon',
  591: 'Carrick',
  592: 'Kerrier',
  593: 'North Cornwall',
  594: 'Penwith',
  595: 'Restormel',
  596: 'Cornwall',
  599: 'Isles of Scilly',
  600: 'Bath',
  601: 'Bristol, City of',
  602: 'Kingswood',
  603: 'Northavon',
  604: 'Wansdyke',
  605: 'North Somerset',
  606: 'Mendip',
  607: 'Sedgemoor',
  608: 'Taunton Deane',
  609: 'West Somerset',
  610: 'South Somerset',
  611: 'Bath and North East Somerset',
  612: 'South Gloucestershire',
  620: 'Cheltenham',
  621: 'Cotswold',
  622: 'Forest of Dean',
  623: 'Gloucester',
  624: 'Stroud',
  625: 'Tewkesbury',
  630: 'Kennet',
  631: 'North Wiltshire',
  632: 'Salisbury',
  633: 'Swindon',
  634: 'West Wiltshire',
  635: 'Wiltshire',
  640: 'Bournemouth',
  641: 'Christchurch',
  642: 'North Dorset',
  643: 'Poole',
  644: 'Purbeck',
  645: 'West Dorset',
  646: 'Weymouth and Portland',
  647: 'East Dorset',
  660: 'Aberconwy',
  661: 'Arfon',
  662: 'Dwyfor',
  663: 'Meirionnydd',
  664: 'Ynys Mon - Isle of Anglesey ',
  665: 'Alyn-Deeside',
  666: 'Colwyn',
  667: 'Delwyn',
  668: 'Glyndwr',
  669: 'Rhuddlan',
  670: 'Wrexham Maelor',
  680: 'Blaenau Gwent',
  682: 'Islwyn',
  683: 'Monmouth',
  684: 'Newport',
  685: 'Torfaen',
  690: 'Cynon Valley',
  692: 'Merthyr Tydfil',
  694: 'Ogwr',
  695: 'Rhondda',
  696: 'Rhymney Valley',
  698: 'Taff-Ely',
  699: 'Cardiff',
  701: 'Vale of Glamorgan',
  702: 'Afan',
  703: 'Lliw Valley',
  704: 'Neath',
  705: 'Swansea ',
  710: 'Carmarthen',
  711: 'Ceredigion',
  712: 'Dinefwr',
  713: 'Llanelli',
  714: 'Preseli',
  715: 'South Pembrokeshire',
  716: 'Brecknock',
  717: 'Montgomery',
  718: 'Radnor',
  720: 'Isle of Anglesey',
  721: 'Conwy',
  722: 'Gwynedd',
  723: 'Denbighshire',
  724: 'Flintshire',
  725: 'Wrexham',
  730: 'Blaenau Gwent',
  731: 'Caerphilly',
  732: 'Monmouthshire',
  733: 'Newport',
  734: 'Torfaen',
  740: 'Bridgend',
  741: 'Cardiff',
  742: 'Merthyr Tydfil',
  743: 'Neath Port Talbot',
  744: 'Rhondda, Cynon, Taff',
  745: 'Swansea',
  746: 'The Vale of Glamorgan',
  750: 'Ceredigion',
  751: 'Carmarthenshire',
  752: 'Pembrokeshire',
  753: 'Powys',
  801: 'Orkney',
  802: 'Shetland',
  803: 'Western Isles',
  804: 'Caithness',
  805: 'Sutherland',
  806: 'Ross and Cromarty',
  807: 'Skye and Lochalsh',
  808: 'Lochaber',
  809: 'Inverness',
  810: 'Badenoch and Strathspey',
  811: 'Nairn',
  812: 'Aberdeen (City of)',
  813: 'Moray',
  814: 'Banff and Buchan',
  815: 'Gordon',
  816: 'Kincardine and Deeside',
  817: 'Dundee (City of)',
  818: 'Angus',
  819: 'Perth and Kinross',
  821: 'Kirkcaldy',
  822: 'North East Fife',
  823: 'Dunfermline ',
  824: 'Edinburgh (City of)',
  825: 'West Lothian',
  826: 'Midlothian',
  827: 'East Lothian',
  828: 'Tweeddale',
  829: 'Ettrick and Lauderdale',
  830: 'Roxburgh',
  831: 'Berwickshire',
  833: 'Clackmannan',
  834: 'Stirling',
  835: 'Falkirk',
  836: 'Glasgow (City of)',
  837: 'Argyll and Bute',
  838: 'Dumbarton',
  839: 'Clydebank',
  840: 'Bearsden and Milngavie',
  841: 'Strathkelvin',
  842: 'Cumbernauld and Kilsyth',
  843: 'Monklands',
  844: 'Motherwell',
  845: 'Hamilton',
  846: 'East Kilbride',
  847: 'Eastwood',
  848: 'Lanark',
  849: 'Renfrew',
  850: 'Inverclyde',
  851: 'Cunninghame',
  852: 'Kilmarnock and Loudoun',
  853: 'Kyle and Carrick',
  854: 'Cumnock and Doon Valley',
  856: 'Wigtown',
  857: 'Stewartry',
  858: 'Nithsdale',
  859: 'Annandale and Eskdale',
  910: 'Aberdeen City',
  911: 'Aberdeenshire',
  912: 'Angus',
  913: 'Argyll and Bute',
  914: 'Scottish Borders',
  915: 'Clackmannanshire',
  916: 'West Dunbartonshire',
  917: 'Dumfries and Galloway',
  918: 'Dundee City',
  919: 'East Ayrshire',
  920: 'East Dunbartonshire',
  921: 'East Lothian',
  922: 'East Renfrewshire',
  923: 'Edinburgh, City of',
  924: 'Falkirk',
  925: 'Fife',
  926: 'Glasgow City',
  927: 'Highland',
  928: 'Inverclyde',
  929: 'Midlothian',
  930: 'Moray',
  931: 'North Ayrshire',
  932: 'North Lanarkshire',
  933: 'Orkney Islands',
  934: 'Perth and Kinross',
  935: 'Renfrewshire',
  936: 'Shetland Islands',
  937: 'South Ayrshire',
  938: 'South Lanarkshire',
  939: 'Stirling',
  940: 'West Lothian',
  941: 'Western Isles',
  -1: 'Code deprecated'},
 'local_authority_ons_district': {'E06000001': 'Hartlepool',
  'E06000002': 'Middlesbrough',
  'E06000003': 'Redcar and Cleveland',
  'E06000004': 'Stockton-on-Tees',
  'E06000005': 'Darlington',
  'E06000006': 'Halton',
  'E06000007': 'Warrington',
  'E06000008': 'Blackburn with Darwen',
  'E06000009': 'Blackpool',
  'E06000010': 'Kingston upon Hull, City of',
  'E06000011': 'East Riding of Yorkshire',
  'E06000012': 'North East Lincolnshire',
  'E06000013': 'North Lincolnshire',
  'E06000014': 'York',
  'E06000015': 'Derby',
  'E06000016': 'Leicester',
  'E06000017': 'Rutland',
  'E06000018': 'Nottingham',
  'E06000019': 'Herefordshire, County of ',
  'E06000020': 'Telford and Wrekin',
  'E06000021': 'Stoke-on-Trent',
  'E06000022': 'Bath and North East Somerset',
  'E06000023': 'Bristol, City of',
  'E06000024': 'North Somerset',
  'E06000025': 'South Gloucestershire',
  'E06000026': 'Plymouth',
  'E06000027': 'Torbay',
  'E06000028': 'Bournemouth',
  'E06000029': 'Poole',
  'E06000030': 'Swindon',
  'E06000031': 'Peterborough',
  'E06000032': 'Luton',
  'E06000033': 'Southend-on-Sea',
  'E06000034': 'Thurrock',
  'E06000035': 'Medway',
  'E06000036': 'Bracknell Forest',
  'E06000037': 'West Berkshire',
  'E06000038': 'Reading',
  'E06000039': 'Slough',
  'E06000040': 'Windsor and Maidenhead',
  'E06000041': 'Wokingham',
  'E06000042': 'Milton Keynes',
  'E06000043': 'Brighton and Hove',
  'E06000044': 'Portsmouth',
  'E06000045': 'Southampton ',
  'E06000046': 'Isle of Wight',
  'E06000047': 'County Durham',
  'E06000048': 'Northumberland',
  'E06000049': 'Cheshire East',
  'E06000050': 'Cheshire West and Chester',
  'E06000051': 'Shropshire',
  'E06000052': 'Cornwall',
  'E06000053': 'Isles of Scilly',
  'E06000054': 'Wiltshire',
  'E06000055': 'Bedford',
  'E06000056': 'Central Bedfordshire',
  'E06000057': 'Northumberland',
  'E06000058': 'Bournemouth, Christchurch and Poole',
  'E06000059': 'Dorset (excluding Christchurch)',
  'E06000060': 'Buckinghamshire',
  'E06000061': 'North Northamptonshire',
  'E06000062': 'West Northamptonshire',
  'E06000063': 'Cumberland',
  'E06000064': 'Westmorland and Furness',
  'E06000065': 'North Yorkshire',
  'E06000066': 'Somerset',
  'E07000001': 'Mid Bedfordshire',
  'E07000002': 'Bedford',
  'E07000003': 'South Bedfordshire',
  'E07000004': 'Aylesbury Vale',
  'E07000005': 'Chiltern',
  'E07000006': 'South Bucks',
  'E07000007': 'Wycombe',
  'E07000008': 'Cambridge',
  'E07000009': 'East Cambridgeshire',
  'E07000010': 'Fenland',
  'E07000011': 'Huntingdonshire',
  'E07000012': 'South Cambridgeshire',
  'E07000019': 'Caradon',
  'E07000020': 'Carrick',
  'E07000021': 'Kerrier',
  'E07000022': 'North Cornwall',
  'E07000023': 'Penwith',
  'E07000024': 'Restormel',
  'E07000026': 'Allerdale',
  'E07000027': 'Barrow-in-Furness',
  'E07000028': 'Carlisle',
  'E07000029': 'Copeland',
  'E07000030': 'Eden',
  'E07000031': 'South Lakeland',
  'E07000032': 'Amber Valley',
  'E07000033': 'Bolsover',
  'E07000034': 'Chesterfield',
  'E07000035': 'Derbyshire Dales',
  'E07000036': 'Erewash',
  'E07000037': 'High Peak',
  'E07000038': 'North East Derbyshire',
  'E07000039': 'South Derbyshire',
  'E07000040': 'East Devon',
  'E07000041': 'Exeter',
  'E07000042': 'Mid Devon',
  'E07000043': 'North Devon',
  'E07000044': 'South Hams',
  'E07000045': 'Teignbridge',
  'E07000046': 'Torridge',
  'E07000047': 'West Devon',
  'E07000048': 'Christchurch',
  'E07000049': 'East Dorset',
  'E07000050': 'North Dorset',
  'E07000051': 'Purbeck',
  'E07000052': 'West Dorset',
  'E07000053': 'Weymouth and Portland',
  'E07000054': 'Chester-le-Street',
  'E07000055': 'Derwentside',
  'E07000056': 'Durham',
  'E07000057': 'Easington',
  'E07000058': 'Sedgefield',
  'E07000059': 'Teesdale',
  'E07000060': 'Wear Valley',
  'E07000061': 'Eastbourne',
  'E07000062': 'Hastings',
  'E07000063': 'Lewes',
  'E07000064': 'Rother',
  'E07000065': 'Wealden',
  'E07000066': 'Basildon',
  'E07000067': 'Braintree',
  'E07000068': 'Brentwood',
  'E07000069': 'Castle Point',
  'E07000070': 'Chelmsford',
  'E07000071': 'Colchester',
  'E07000072': 'Epping Forest',
  'E07000073': 'Harlow',
  'E07000074': 'Maldon',
  'E07000075': 'Rochford',
  'E07000076': 'Tendring',
  'E07000077': 'Uttlesford',
  'E07000078': 'Cheltenham',
  'E07000079': 'Cotswold',
  'E07000080': 'Forest of Dean',
  'E07000081': 'Gloucester',
  'E07000082': 'Stroud',
  'E07000083': 'Tewkesbury',
  'E07000084': 'Basingstoke and Deane',
  'E07000085': 'East Hampshire',
  'E07000086': 'Eastleigh',
  'E07000087': 'Fareham',
  'E07000088': 'Gosport',
  'E07000089': 'Hart',
  'E07000090': 'Havant',
  'E07000091': 'New Forest',
  'E07000092': 'Rushmoor',
  'E07000093': 'Test Valley',
  'E07000094': 'Winchester',
  'E07000095': 'Broxbourne',
  'E07000096': 'Dacorum',
  'E07000097': 'East Hertfordshire',
  'E07000098': 'Hertsmere',
  'E07000099': 'North Hertfordshire',
  'E07000100': 'St Albans',
  'E07000101': 'Stevenage',
  'E07000102': 'Three Rivers',
  'E07000103': 'Watford',
  'E07000104': 'Welwyn Hatfield',
  'E07000105': 'Ashford',
  'E07000106': 'Canterbury',
  'E07000107': 'Dartford',
  'E07000108': 'Dover',
  'E07000109': 'Gravesham',
  'E07000110': 'Maidstone',
  'E07000111': 'Sevenoaks',
  'E07000112': 'Shepway',
  'E07000113': 'Swale',
  'E07000114': 'Thanet',
  'E07000115': 'Tonbridge and Malling',
  'E07000116': 'Tunbridge Wells',
  'E07000117': 'Burnley',
  'E07000118': 'Chorley',
  'E07000119': 'Fylde',
  'E07000120': 'Hyndburn',
  'E07000121': 'Lancaster',
  'E07000122': 'Pendle',
  'E07000123': 'Preston',
  'E07000124': 'Ribble Valley',
  'E07000125': 'Rossendale',
  'E07000126': 'South Ribble',
  'E07000127': 'West Lancashire',
  'E07000128': 'Wyre',
  'E07000129': 'Blaby',
  'E07000130': 'Charnwood',
  'E07000131': 'Harborough',
  'E07000132': 'Hinckley and Bosworth',
  'E07000133': 'Melton',
  'E07000134': 'North West Leicestershire',
  'E07000135': 'Oadby and Wigston',
  'E07000136': 'Boston',
  'E07000137': 'East Lindsey',
  'E07000138': 'Lincoln',
  'E07000139': 'North Kesteven',
  'E07000140': 'South Holland',
  'E07000141': 'South Kesteven',
  'E07000142': 'West Lindsey',
  'E07000143': 'Breckland',
  'E07000144': 'Broadland',
  'E07000145': 'Great Yarmouth',
  'E07000146': "King's Lynn and West Norfolk",
  'E07000147': 'North Norfolk',
  'E07000148': 'Norwich',
  'E07000149': 'South Norfolk',
  'E07000150': 'Corby',
  'E07000151': 'Daventry',
  'E07000152': 'East Northamptonshire',
  'E07000153': 'Kettering',
  'E07000154': 'Northampton',
  'E07000155': 'South Northamptonshire',
  'E07000156': 'Wellingborough',
  'E07000163': 'Craven',
  'E07000164': 'Hambleton',
  'E07000165': 'Harrogate',
  'E07000166': 'Richmondshire',
  'E07000167': 'Ryedale',
  'E07000168': 'Scarborough',
  'E07000169': 'Selby',
  'E07000170': 'Ashfield',
  'E07000171': 'Bassetlaw',
  'E07000172': 'Broxtowe',
  'E07000173': 'Gedling',

### Evaluación de la calidad de los datos y limpieza

- Porcentaje de valores nulos

In [18]:
(collision.isna().sum() / collision.shape[0] * 100).loc[lambda x: x > 0]

location_easting_osgr              0.01291
location_northing_osgr             0.01291
longitude                          0.01291
latitude                           0.01291
local_authority_highway_current    0.01589
dtype: float64

In [19]:
(casualty.isna().sum() / casualty.shape[0] * 100).loc[lambda x: x > 0]

Series([], dtype: float64)

In [20]:
(vehicle.isna().sum() / vehicle.shape[0] * 100).loc[lambda x: x > 0]

Series([], dtype: float64)

Casi no hay valores nulos en el dataset de colisiones. Como solo vamos a perder 80 filas las quitamos para que no molesten.

In [21]:
collision.shape[0] - collision.dropna().shape[0]

80

Aprovechamos a crear las copias de los datasets sobre los que vamos a trabajar la limpieza

In [22]:
collision_cln = collision.copy()
casualty_cln = casualty.copy()
vehicle_cln = vehicle.copy()

In [23]:
collision_cln = collision_cln.dropna()

- Comprobamos duplicados

In [24]:
collision_cln.duplicated().sum()

np.int64(0)

In [25]:
casualty_cln.duplicated().sum()

np.int64(0)

In [26]:
vehicle_cln.duplicated().sum()

np.int64(0)

- Miramos que no haya un solo valor en las variables categóricas

In [27]:
collision_cln[collision_value_map.keys()].nunique()

police_force                                          44
collision_severity                                     3
date                                                1827
day_of_week                                            7
time                                                1440
local_authority_district                             377
local_authority_ons_district                         375
local_authority_highway                              210
local_authority_highway_current                      207
first_road_class                                       6
first_road_number                                   3618
road_type                                              6
speed_limit                                            7
junction_detail_historic                              11
junction_detail                                        8
junction_control                                       6
second_road_class                                      8
second_road_number                                  3327
pedestrian_crossing_human_control_historic             5
pedestrian_crossing_physical_facilities_historic       8
pedestrian_crossing                                   10
light_conditions                                       6
weather_conditions                                    10
road_surface_conditions                                7
special_conditions_at_site                            10
carriageway_hazards_historic                           8
carriageway_hazards                                   14
urban_or_rural_area                                    2
did_police_officer_attend_scene_of_accident            4
trunk_road_flag                                        3
collision_injury_based                                 2
dtype: int64

In [28]:
casualty_cln[casualty_value_map.keys()].nunique()

casualty_class                          3
sex_of_casualty                         4
age_of_casualty                       103
age_band_of_casualty                   12
casualty_severity                       3
pedestrian_location                    12
pedestrian_movement                    11
car_passenger                           5
bus_or_coach_passenger                  7
pedestrian_road_maintenance_worker      4
casualty_type                          23
casualty_imd_decile                    11
enhanced_casualty_severity              6
casualty_injury_based                   2
casualty_distance_banding               6
dtype: int64

In [29]:
vehicle_cln[vehicle_value_map.keys()].nunique()

vehicle_type                                   22
towing_and_articulation                         8
vehicle_manoeuvre_historic                     20
vehicle_manoeuvre                              19
vehicle_direction_from                         11
vehicle_direction_to                           11
vehicle_location_restricted_lane_historic      12
vehicle_location_restricted_lane                9
junction_location                              11
skidding_and_overturning                        8
hit_object_in_carriageway                      14
vehicle_leaving_carriageway                    11
hit_object_off_carriageway                     14
first_point_of_impact                           7
vehicle_left_hand_drive                         4
journey_purpose_of_driver_historic              7
journey_purpose_of_driver                       7
sex_of_driver                                   4
age_of_driver                                 102
age_band_of_driver                             12
engine_capacity_cc                           1515
propulsion_code                                13
generic_make_model                           1057
driver_imd_decile                              11
escooter_flag                                   2
driver_distance_banding                         6
dtype: int64

Las categorías desconocidas y valores faltantes están marcados como -1. Vamos a comprobar la cantidad de esos valores para ver si suponen un problema

In [30]:
(collision_cln == -1).mean().mul(100).loc[lambda x: x > 0].sort_values(ascending=False)

local_authority_district                            82.043524
enhanced_severity_collision                         47.926181
junction_control                                    42.048093
second_road_number                                  37.941775
special_conditions_at_site                          12.659641
carriageway_hazards_historic                        12.658250
pedestrian_crossing_human_control_historic          12.550383
pedestrian_crossing_physical_facilities_historic    12.543231
junction_detail_historic                            11.840602
trunk_road_flag                                      7.128200
junction_detail                                      2.938249
second_road_class                                    2.279125
pedestrian_crossing                                  0.962068
carriageway_hazards                                  0.941805
road_surface_conditions                              0.637273
light_conditions                                     0.003774
speed_limit                                          0.002980
weather_conditions                                   0.002582
did_police_officer_attend_scene_of_accident          0.000199
dtype: float64

Observaciones:

Las columnas ***local_authority_district***, ***junction_control***, ***second_road_number*** tienen un alto porcentaje de valores desconocidos.

In [31]:
(casualty_cln == -1).mean().mul(100).loc[lambda x: x > 0].sort_values(ascending=False)

casualty_distance_banding             82.670853
enhanced_casualty_severity            42.311271
casualty_imd_decile                   10.847871
age_of_casualty                        2.161674
age_band_of_casualty                   2.161674
pedestrian_road_maintenance_worker     1.885493
sex_of_casualty                        0.896144
casualty_type                          0.770465
car_passenger                          0.427308
bus_or_coach_passenger                 0.039811
pedestrian_location                    0.002186
pedestrian_movement                    0.002030
dtype: float64

In [32]:
(vehicle_cln == -1).mean().mul(100).loc[lambda x: x > 0].sort_values(ascending=False)

driver_distance_banding                      84.468422
engine_capacity_cc                           25.387969
age_of_vehicle                               24.159328
propulsion_code                              24.134021
driver_imd_decile                            20.569854
age_of_driver                                14.915086
age_band_of_driver                           14.915086
vehicle_manoeuvre_historic                   12.741938
vehicle_location_restricted_lane_historic    12.493972
journey_purpose_of_driver_historic           11.938194
vehicle_direction_to                          2.043029
vehicle_direction_from                        2.028909
vehicle_manoeuvre                             1.339753
first_point_of_impact                         1.278386
vehicle_location_restricted_lane              1.155327
vehicle_leaving_carriageway                   1.098847
skidding_and_overturning                      1.096241
hit_object_in_carriageway                     1.088529
towing_and_articulation                       0.814605
vehicle_type                                  0.710878
junction_location                             0.455744
sex_of_driver                                 0.385688
journey_purpose_of_driver                     0.198438
hit_object_off_carriageway                    0.197460
vehicle_left_hand_drive                       0.102097
dtype: float64

Observaciones:

La columna ***driver_distance_banding*** tiene un alto porcentaje de valores desconocidos.

- Conversiones de tipos

Vamos a juntar las columnas *date* y *time* que actualmente son del tipo *str* en una nueva columna que sea *date_time*

In [33]:
collision_cln[['date', 'time']].head()

         date   time
0  22/05/2021  22:44
1  20/10/2021  15:50
2  01/12/2020  18:00
3  09/12/2021  16:55
4  12/04/2021  09:02

In [34]:
collision_cln[['date', 'time']].info()

<class 'pandas.DataFrame'>
Index: 503395 entries, 0 to 503474
Data columns (total 2 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   date    503395 non-null  str
 1   time    503395 non-null  str
dtypes: str(2)
memory usage: 18.8 MB

In [35]:
collision_cln["date_time"] = pd.to_datetime(collision_cln["date"] + " " + collision_cln["time"], format="%d/%m/%Y %H:%M")

In [36]:
collision_cln["date_time"]

0        2021-05-22 22:44:00
1        2021-10-20 15:50:00
2        2020-12-01 18:00:00
3        2021-12-09 16:55:00
4        2021-04-12 09:02:00
                 ...
503470   2021-09-11 01:15:00
503471   2022-02-04 14:36:00
503472   2022-07-22 15:15:00
503473   2023-01-27 06:45:00
503474   2024-06-24 17:00:00
Name: date_time, Length: 503395, dtype: datetime64[us]

In [37]:
date_time = collision_cln.pop('date_time')
collision_cln.insert(2, 'date_time', date_time)
collision_cln.head()

,collision_index,collision_year,date_time,collision_ref_no,location_easting_osgr,location_northing_osgr,longitude,latitude,police_force,collision_severity,number_of_vehicles,number_of_casualties,date,day_of_week,time,local_authority_district,local_authority_ons_district,local_authority_highway,local_authority_highway_current,first_road_class,first_road_number,road_type,speed_limit,junction_detail_historic,junction_detail,junction_control,second_road_class,second_road_number,pedestrian_crossing_human_control_historic,pedestrian_crossing_physical_facilities_historic,pedestrian_crossing,light_conditions,weather_conditions,road_surface_conditions,special_conditions_at_site,carriageway_hazards_historic,carriageway_hazards,urban_or_rural_area,did_police_officer_attend_scene_of_accident,trunk_road_flag,lsoa_of_accident_location,enhanced_severity_collision,collision_injury_based,collision_adjusted_severity_serious,collision_adjusted_severity_slight
0,2021170H10421,2021,2021-05-22 22:44:00,170H10421,447098.0,532997.0,-1.270905,54.689833,17,3,2,2,22/05/2021,7,22:44,-1,E06000001,E06000001,E06000001,6,0,6,60,0,0,-1,0,-1,0,0,0,6,1,1,0,0,0,2,1,2,E01011959,-1,0,0.293588,0.706412
1,2021170H11231,2021,2021-10-20 15:50:00,170H11231,450486.0,533118.0,-1.218333,54.690592,17,3,2,1,20/10/2021,4,15:50,-1,E06000001,E06000001,E06000001,4,1277,6,30,6,16,2,5,0,0,0,0,1,1,1,0,0,0,1,2,2,E01011973,-1,0,0.017448,0.982552
2,2020170M11750,2020,2020-12-01 18:00:00,170M11750,449694.0,519733.0,-1.232884,54.570397,17,3,2,1,01/12/2020,3,18:00,243,E06000002,E06000002,E06000002,6,0,6,20,6,16,4,6,0,0,0,0,4,1,1,0,0,0,1,1,2,E01012092,-1,0,0.128730,0.871270
3,2021170M31761,2021,2021-12-09 16:55:00,170M31761,449744.0,514217.0,-1.233040,54.520825,17,3,1,1,09/12/2021,5,16:55,-1,E06000002,E06000002,E06000002,5,0,6,40,0,0,-1,0,-1,0,0,0,4,1,2,0,0,0,2,1,2,E01032553,-1,0,0.182698,0.817302
4,2021170S10441,2021,2021-04-12 09:02:00,170S10441,445971.0,520834.0,-1.290292,54.580641,17,3,3,1,12/04/2021,2,09:02,-1,E06000004,E06000004,E06000004,3,19,3,70,0,0,-1,0,-1,0,0,0,1,1,1,4,0,13,2,1,1,E01012258,-1,0,0.016094,0.983906

Convertimos el limite de velocidad de la vía a int

In [38]:
collision_cln['speed_limit'] = collision_cln['speed_limit'].astype(int)
collision_cln['speed_limit'].dtype

dtype('int64')

### Preparación de variables para las hipótesis planteadas
- La dirección del choque influye en tasa de mortalidad del los accidentes
- A más velocidad maxima de la via más accidentes con heridos graves o fatales
- La distribución de accidentes a lo largo del año sigue un patron repetitivo para todos los años
- Los accidentes fatales se concentran en ciertas localidades
- Los motoristas y peatones representan un porcentaje alto de las víctimas fatales respecto a su participación en el tráfico

Eliminaremos las variables redundantes y las que no aporten valor para analizar las hipótesis mencionadas

In [39]:
unw_cols_collision = [
    'date',
    'time',
    'collision_year',
    'collision_ref_no',
    'location_easting_osgr',
    'location_northing_osgr',
    'local_authority_district',
    'local_authority_highway_current',
    #'first_road_number',
    'second_road_number',
    'pedestrian_crossing_human_control_historic',
    'pedestrian_crossing_physical_facilities_historic',
    'carriageway_hazards_historic',
    'junction_detail_historic',
    'collision_adjusted_severity_serious',
    'collision_adjusted_severity_slight',
    'lsoa_of_accident_location',
    'enhanced_severity_collision',
    'collision_injury_based',
    'pedestrian_crossing',
    'special_conditions_at_site',
    'carriageway_hazards',
    'did_police_officer_attend_scene_of_accident',
    'trunk_road_flag',
]
print(collision_cln.shape)
collision_cln = collision_cln.drop(columns=unw_cols_collision)
print(collision_cln.shape)
collision_cln.head()

(503395, 45)
(503395, 22)

,collision_index,date_time,longitude,latitude,police_force,collision_severity,number_of_vehicles,number_of_casualties,day_of_week,local_authority_ons_district,local_authority_highway,first_road_class,first_road_number,road_type,speed_limit,junction_detail,junction_control,second_road_class,light_conditions,weather_conditions,road_surface_conditions,urban_or_rural_area
0,2021170H10421,2021-05-22 22:44:00,-1.270905,54.689833,17,3,2,2,7,E06000001,E06000001,6,0,6,60,0,-1,0,6,1,1,2
1,2021170H11231,2021-10-20 15:50:00,-1.218333,54.690592,17,3,2,1,4,E06000001,E06000001,4,1277,6,30,16,2,5,1,1,1,1
2,2020170M11750,2020-12-01 18:00:00,-1.232884,54.570397,17,3,2,1,3,E06000002,E06000002,6,0,6,20,16,4,6,4,1,1,1
3,2021170M31761,2021-12-09 16:55:00,-1.233040,54.520825,17,3,1,1,5,E06000002,E06000002,5,0,6,40,0,-1,0,4,1,2,2
4,2021170S10441,2021-04-12 09:02:00,-1.290292,54.580641,17,3,3,1,2,E06000004,E06000004,3,19,3,70,0,-1,0,1,1,1,2

In [40]:
unw_cols_casualty = [
    'casualty_reference',
    'vehicle_reference',
    'lsoa_of_casualty',
    'casualty_distance_banding',
    'casualty_injury_based',
    'collision_year',
    'collision_ref_no',
    'casualty_adjusted_severity_serious',
    'casualty_adjusted_severity_slight',
    'pedestrian_location', 'pedestrian_movement',
    'car_passenger',
    'bus_or_coach_passenger',
    'pedestrian_road_maintenance_worker',
    'casualty_imd_decile'
]
print(casualty_cln.shape)
casualty_cln  = casualty_cln.drop(columns=unw_cols_casualty)
print(casualty_cln.shape)
casualty_cln.head()

(640522, 23)
(640522, 8)

,collision_index,casualty_class,sex_of_casualty,age_of_casualty,age_band_of_casualty,casualty_severity,casualty_type,enhanced_casualty_severity
0,2020010280094,3,2,24,5,3,0,-1
1,202031D109620,3,2,95,11,2,0,-1
2,2020401003715,3,1,39,7,3,0,3
3,2021201086330,3,1,63,9,3,0,3
4,2021371050963,3,1,51,8,3,0,3

In [41]:
unw_cols_vehicle = [
    'collision_ref_no',
    'vehicle_reference',
    'generic_make_model',
    'driver_imd_decile',
    'lsoa_of_driver',
    'driver_distance_banding',
    'towing_and_articulation',
    'vehicle_left_hand_drive',
    'journey_purpose_of_driver_historic',
    'vehicle_manoeuvre_historic',
    'collision_year',
    'vehicle_direction_from',
    'vehicle_direction_to',
    'vehicle_location_restricted_lane_historic',
    'vehicle_location_restricted_lane',
    'junction_location',
    'skidding_and_overturning',
    'hit_object_in_carriageway',
    #'vehicle_leaving_carriageway',
    #'hit_object_off_carriageway',
    'journey_purpose_of_driver',
    'engine_capacity_cc',
    'propulsion_code',
    'age_of_vehicle',
    'escooter_flag'
]
print(vehicle_cln.shape)
vehicle_cln = vehicle_cln.drop(columns=unw_cols_vehicle, errors='ignore')
print(vehicle_cln.shape)
vehicle_cln.head()

(920692, 32)
(920692, 9)

,collision_index,vehicle_type,vehicle_manoeuvre,vehicle_leaving_carriageway,hit_object_off_carriageway,first_point_of_impact,sex_of_driver,age_of_driver,age_band_of_driver
0,2020210979534,5,3,0,0,2,1,57,9
1,2020030959800,5,19,1,0,1,1,59,9
2,2020360978858,5,19,0,0,1,1,64,9
3,2020430340711,5,19,7,4,1,1,48,8
4,2020010260297,5,99,9,99,9,1,36,7

### Exportación
Exportamos los datasets reducidos y limpios que usaremos para analizar las hipótesis. Filtraremos mas cuidadosamente las variables cuando estemos analizando cada  hipotesis por separado.

In [42]:
collision_cln.to_parquet('../data/processed/uk_collision_cln.parquet', index=False)
casualty_cln.to_parquet('../data/processed/uk_casualty_cln.parquet', index=False)
vehicle_cln.to_parquet('../data/processed/uk_vehicle_cln.parquet', index=False)